# Generated by Django 4.1.2 on 2022-10-08 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre_title', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='movie title')),
                ('year', models.BigIntegerField(verbose_name='released year')),
                ('rating', models.IntegerField(verbose_name='rating')),
                ('genres', models.ManyToManyField(to='main_app.genre', verbose_name='Genre')),
            ],
        ),
    ]
